// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string  `json:"id"`
	Text            string  `json:"text"`
	ParentCommentID *string `json:"parentCommentID,omitempty"`
	PostID          string  `json:"postID"`
	UserID          string  `json:"userID"`
}

type DisableCommentsRequest struct {
	UserID string `json:"userID"`
	PostID string `json:"postID"`
}

type Mutation struct {
}

type NewComment struct {
	Text            string  `json:"text"`
	ParentCommentID *string `json:"parentCommentID,omitempty"`
	PostID          string  `json:"postID"`
	UserID          string  `json:"userID"`
}

type NewPost struct {
	Text        string `json:"text"`
	UserID      string `json:"userID"`
	CommentsOff *bool  `json:"commentsOff,omitempty"`
}

type Post struct {
	ID          string `json:"id"`
	Text        string `json:"text"`
	UserID      string `json:"userID"`
	CommentsOff bool   `json:"commentsOff"`
}

type PostsSubscribeInput struct {
	PostIDs []string `json:"postIDs"`
}

type Query struct {
}

type Subscription struct {
}
